# Generated by Django 3.1.4 on 2020-12-18 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizTakers',
            fields=[
                ('quizTakerId', models.AutoField(primary_key=True, serialize=False)),
                ('quizSetAttempted', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('isPassed', models.BooleanField(default=False)),
                ('isCompleted', models.BooleanField(default=False)),
                ('totaltime', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
    ]
