# Generated by Django 3.1.4 on 2020-12-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_auto_20201218_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='quizSetAttempted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.quizset'),
        ),
    ]
