# Generated by Django 3.1.4 on 2020-12-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
