# Generated by Django 3.1.4 on 2020-12-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0007_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='quizQuestion',
            new_name='quizQuestionId',
        ),
    ]
