# Generated by Django 3.1.4 on 2020-12-19 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0008_auto_20201218_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='AttemptedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
